# Generated by Django 4.1.6 on 2023-02-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_venue', models.CharField(max_length=100)),
                ('event_time', models.CharField(max_length=100)),
                ('event_image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
