# Generated by Django 4.1.6 on 2023-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0002_orgbookevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbookevents',
            name='organisation_name',
        ),
        migrations.AddField(
            model_name='orgbookevents',
            name='attendance_mode',
            field=models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual'), ('student', 'Student')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
