# Generated by Django 4.1.6 on 2023-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0003_remove_orgbookevents_organisation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookevents',
            name='full_names',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
