# Generated by Django 4.1.6 on 2023-02-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0005_rename_amount_paid_orgbookevents_booking_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookevents',
            name='event',
            field=models.CharField(choices=[('choose', 'Choose Event'), ('women-led', '1ST WOMEN LEAD CONFERENCE')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
