# Generated by Django 4.1.6 on 2023-02-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0006_orgbookevents_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookevents',
            name='booking_status',
            field=models.CharField(default='Not Approved', max_length=20),
        ),
    ]
