# Generated by Django 4.1.6 on 2023-02-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0008_mpesatransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbookevents',
            name='booking_amount',
        ),
    ]
