# Generated by Django 4.1.6 on 2023-02-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0011_lnmonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookevents',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
