# Generated by Django 4.1.6 on 2023-02-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0012_orgbookevents_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbookevents',
            name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='orgbookevents',
            name='transaction_id',
        ),
    ]
