# Generated by Django 4.1.6 on 2023-02-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0013_remove_orgbookevents_mode_of_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LNMOnline',
        ),
        migrations.DeleteModel(
            name='MpesaTransaction',
        ),
        migrations.RenameField(
            model_name='orgbookevents',
            old_name='full_names',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='orgbookevents',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgbookevents',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
