# Generated by Django 4.1.6 on 2023-02-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0014_delete_lnmonline_delete_mpesatransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbookevents',
            name='middle_name',
        ),
    ]
