# Generated by Django 4.1.6 on 2023-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0016_orgbookevents_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookevents',
            name='university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgbookevents',
            name='year_of_study',
            field=models.CharField(choices=[('first', '1ST YEAR'), ('second', '2ND YEAR'), ('third', '3RD YEAR'), ('fourth', '4TH YEAR'), ('fifth', '5TH YEAR')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgbookevents',
            name='currency',
            field=models.CharField(choices=[('kes', 'KES'), ('usd', 'USD')], max_length=3),
        ),
    ]
