# Generated by Django 4.1.6 on 2023-02-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0017_orgbookevents_university_orgbookevents_year_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookevents',
            name='organization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orgbookevents',
            name='university',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orgbookevents',
            name='year_of_study',
            field=models.CharField(choices=[('first', '1ST YEAR'), ('second', '2ND YEAR'), ('third', '3RD YEAR'), ('fourth', '4TH YEAR'), ('fifth', '5TH YEAR')], default='', max_length=10),
        ),
    ]
