# Generated by Django 4.1.6 on 2023-02-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0018_orgbookevents_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbookevents',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orgbookevents',
            name='university',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orgbookevents',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('first', '1ST YEAR'), ('second', '2ND YEAR'), ('third', '3RD YEAR'), ('fourth', '4TH YEAR'), ('fifth', '5TH YEAR')], max_length=10),
        ),
    ]
