# Generated by Django 4.1.6 on 2023-09-29 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0019_alter_orgbookevents_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookevents',
            name='date_booking',
            field=models.DateField(default=datetime.date.today, max_length=100),
        ),
    ]
