# Generated by Django 4.1.6 on 2023-12-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0020_orgbookevents_date_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbookevents',
            name='email_address',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='MakePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
                ('order_amount', models.IntegerField()),
                ('confirmation_code', models.CharField(max_length=100, unique=True)),
                ('status_code', models.CharField(max_length=5)),
                ('order_currency', models.CharField(max_length=20)),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainEvents.orgbookevents')),
            ],
        ),
    ]
