# Generated by Django 4.1.6 on 2023-12-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0021_alter_orgbookevents_email_address_makepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbookevents',
            name='email_address',
            field=models.EmailField(max_length=100),
        ),
    ]
