# Generated by Django 4.1.6 on 2023-12-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainEvents', '0022_alter_orgbookevents_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='email_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TrainEvents.orgbookevents'),
        ),
    ]
